### PR TITLE
:sparkles: change background color

### LINKED ISSUE #1: Change Background color
@MitchelleChepkemoi, we need to change the background color as discussed.
Please send me the color code.

### PR DESCRIPTION
**Pull request by kbuika**
This PR resolves issue #1

### CODE REVIEW

**Comment by charleskirash** [comment]
shwaari

**Comment by MitchelleChepkemoi** [comment]
I approve 💯

**Review by charleskirash — DISMISSED** [review]
iko shwaare

**Review by MitchelleChepkemoi — DISMISSED** [review]
I approve

**Review by leehonel — CHANGES_REQUESTED** [review]
Pick a different color

**Review by leehonel — APPROVED** [review]
That can work,

**Review by MitchelleChepkemoi — APPROVED** [review]
Nice 💯

**Pull request merged**
