### PR TITLE
:sparkles: Lecture cards build

### PR DESCRIPTION
**Pull request by kbuika**
This PR adds the lecture cards build.
It also adds some of the resources like icons, etc.

@winniekagz I mistook the pages and worked on the Lecture cards instead of the Events cards. 

Here is a preview of how the page looks like in mobile

image

### CODE REVIEW

**Review by winniekagz — APPROVED** [review]
ok

**Review by winniekagz — COMMENTED** [review]
@kibuikaCodes  in app.js you have imported react twice

**Comment by kbuika** [comment]
Let me fix it.

**Comment by kbuika** [comment]
> @kibuikaCodes  in app.js you have imported react twice

@winniekagz I have not imported twice. I think you are looking at the tree changes.

**Review by MitchelleChepkemoi — APPROVED** [review]

**Pull request merged**
