### PR TITLE
upcoming events update

### PR DESCRIPTION
**Pull request by winniekagz**
upcoming events page created

### CODE REVIEW

**Review by leehonel — DISMISSED** [review]
I choose to trust your judgement

**Comment by kbuika** [comment]
Good work. Though there is no preview.
But merge my pr before merging this one. 👍🏾

**Review by kbuika — DISMISSED** [review]
Good work.

**Review by MitchelleChepkemoi — APPROVED** [review]
I am just gonna approve, Kibuika will check if changes should be made!

**Comment by kbuika** [comment]
@winniekagz why did you force push?

and also, I am waiting for your review on my pull request. We should combine this, and start on the middleware for sending push notifications to Whatsapp.

**Review by charleskirash — APPROVED** [review]
I trust your judgement

**Comment by kbuika** [comment]
@winniekagz we need to fix the conflicts, if it will be tricky, I can do it for you.

**Review by kbuika — CHANGES_REQUESTED** [review]
Fix conflict

**Comment by winniekagz** [comment]
> Fix conflict

lemmi work on it

**Comment by kbuika** [comment]
Cool
Watch out you don't lose your code

**Pull request closed without merging**
